name: Continuos Deployment workflow

on:
  push:
    branches:
      - main
env:
  HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
